{
 "title": "ArgoCD Overview",
 "tags": [ "argocd" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "ArgoCD Applications",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(argocd_app_info)" }
   ]
  },
  {
   "title": "Apps Synced",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(argocd_app_info{sync_status=\"Synced\"})"
    }
   ]
  },
  {
   "title": "Apps OutOfSync",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(argocd_app_info{sync_status=\"OutOfSync\"})"
    }
   ]
  },
  {
   "title": "ArgoCD Applications status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "argocd_app_info", "legendFormat": "{{ name }} ({{ sync_status }})" }
   ]
  }
 ]
}